platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64
  - npm install

build_script:
  - npm run dist

test: off

skip_non_tags: true